#!/usr/bin/env bash

ln -sf ~/dotfiles/nvim ~/.config/
ln -sf ~/dotfiles/quickshell ~/.config
# Figure out how to get hypr to detect changes in a symlink
ln -sf ~/dotfiles/hypr ~/.config
ln -sf ~/dotfiles/tmux/scripts ~/.tmux/
ln -sf ~/dotfiles/tmux/.tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/zsh/.zshrc ~/.zshrc
ln -sf ~/dotfiles/kitty/kitty.conf ~/.config/kitty/kitty.conf
ln -sf ~/dotfiles/idea/.ideavimrc ~/.ideavimrc

chmod +x ~/dotfiles/tmux/scripts/sessionizer.sh
