return {
	{
		"supermaven-inc/supermaven-nvim",
		enabled = true,
		config = function()
			require("supermaven-nvim").setup({
				disable_inline_completion = true, -- disables inline completion for use with cmp
				disable_keymaps = true, -- disables built in keymaps for more manual control
			})
		end,
	},
	{
		"milanglacier/minuet-ai.nvim",
		enabled = false,
		config = function()
			require("minuet").setup({
				blink = {
					enable_auto_complete = true,
				},
				provider = "codestral",
				-- the maximum total characters of the context before and after the cursor
				-- 16000 characters typically equate to approximately 4,000 tokens for
				-- LLMs.
				context_window = 16000,
				-- when the total characters exceed the context window, the ratio of
				-- context before cursor and after cursor, the larger the ratio the more
				-- context before cursor will be used. This option should be between 0 and
				-- 1, context_ratio = 0.75 means the ratio will be 3:1.
				context_ratio = 0.75,
				throttle = 1000, -- only send the request every x milliseconds, use 0 to disable throttle.
				-- debounce the request in x milliseconds, set to 0 to disable debounce
				debounce = 400,
				-- The request timeout, measured in seconds. When streaming is enabled
				-- (stream = true), setting a shorter request_timeout allows for faster
				-- retrieval of completion items, albeit potentially incomplete.
				-- Conversely, with streaming disabled (stream = false), a timeout
				-- occurring before the LLM returns results will yield no completion items.
				request_timeout = 3,
				-- If completion item has multiple lines, create another completion item
				-- only containing its first line. This option only has impact for cmp and
				-- blink. For virtualtext, no single line entry will be added.
				add_single_line_entry = true,
				-- The number of completion items encoded as part of the prompt for the
				-- chat LLM. For FIM model, this is the number of requests to send. It's
				-- important to note that when 'add_single_line_entry' is set to true, the
				-- actual number of returned items may exceed this value. Additionally, the
				-- LLM cannot guarantee the exact number of completion items specified, as
				-- this parameter serves only as a prompt guideline.
				n_completions = 1,
				-- Defines the length of non-whitespace context after the cursor used to
				-- filter completion text. Set to 0 to disable filtering.
				--
				-- Example: With after_cursor_filter_length = 3 and context:
				--
				-- "def fib(n):\n|\n\nfib(5)" (where | represents cursor position),
				--
				-- if the completion text contains "fib", then "fib" and subsequent text
				-- will be removed. This setting filters repeated text generated by the
				-- LLM. A large value (e.g., 15) is recommended to avoid false positives.
				after_cursor_filter_length = 15,
				provider_options = {
					codestral = {
						model = "codestral-2501",
						end_point = "https://codestral.mistral.ai/v1/fim/completions",
						api_key = "CODESTRAL_API_KEY",
						stream = true,
						optional = {
							stop = { "\n\n" }, -- the identifier to stop the completion generation
							max_tokens = 256,
						},
					},
				},
			})
		end,
	},
}
